name: Compilar y Subir app

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      matrix:
        node-version: [12.x]
    steps: 
    - uses: actions/checkout@v2
    - id: release
      uses: rymndhng/release-on-push-action@master
      with:
        bump_version_scheme: minor
    - name: Obtener vesion
      run: |
        ex -s -c '%s/{{ci-version}}/${{ steps.release.outputs.tag_name }}/g|x' app.component.ts
      
      
    - name: Cache node modules
      uses: actions/cache@v1
      with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
    - name: Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
          node-version: ${{ matrix.node-version }}
    
    - name: Compilando app
      run: |
          yarn install
          yarn run build -c production
          
    - name: Creando imagen de docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ezequiel2point0/edm
        tags: ${{ steps.release.outputs.version }}

